	{description:"dark hair"},
	{description:"red hair"},
	{description:"blonde hair"},
	{description:"bald"},
	{description:"long hair"},
	{description:"medium hair"},
	{description:"short hair"},
	{description:"beard"},
	{description:"mustache"},
	{description:"clean shaven"},
	{description:"dark eyes"},
	{description:"green eyes"},
	{description:"blue eyes"},
	{description:"hazel eyes"},
	{description:"colored contacts"},
	{description:"dark skin"},
	{description:"brown skin"},
	{description:"light skin"},
	{description:"has glasses"},
	{description:"male"},
	{description:"female"},
	{description:"is tall"},
	{description:"is short"},
	{description:"pc computer"},
	{description:"mac computer"},
	{description:"younger than 30"},
	{description:"native new yorker"},
	{description:"single"},
	{description:"dating someone"},
	{description:"married"},
	{description:"prefers pepperoni pizza"},
	{description:"prefers cheese pizza"},
	{description:"has earrings"},
	{description:"has tattoos"},
	{description:"grey hair"}])